# -*- coding: utf-8 -*-
"""BotDiscord

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vYpR9F1ugrKDMQ_v23KnkD43eDoAXuQQ
"""

!pip install discord.py
!pip install nest_asyncio

import nest_asyncio 
nest_asyncio.apply()
import discord

client = discord.Client()

intents = discord.Intents.all()

intents = discord.Intents.default()
intents.messages = True
intents.members = True
intents.typing = True
client = discord.Client(intents=intents)

@client.event
async def on_ready():
    print("Le bot est prêt !")

@client.event
async def on_typing(channel, user, when):
     await channel.send(user.name+" is typing")

@client.event
async def on_member_join(member):
    general_channel = client.get_channel(1044971353574477954)
    await general_channel.send("Bienvenue sur le serveur ! "+ member.name)

@client.event
async def on_message(message):
  if message.author == client.user:
    return
  
  await message.channel.send("Hello")
  
  message.content = message.content.lower()

  if message.content.startswith("test"):
    await message.channel.send("Hello")

  if "cochon" in message.content:
    await message.channel.send("Gagné !")

  if message.content == "azerty":
    await message.channel.send("qwerty")

client.run("MTA0NDk2ODYyMjUzMzEyODI0Mw.G2pbfK.RfhQSh_bKXUU9eq0jXtD2TWRvwSs-xbop6sGsA")